server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true #attiva il circuit-breaker tutti client Openfeign di Accounts

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health: # abiita la ricezione della condizione di liveness e readness dell'applicazione
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/



info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        accounts: DEBUG #Tutti i log di gatewayserver saranno di livello DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

#abilita il pattern retry per eventuali metodi annotati con retry nell'Accounts MS(Quindi non tramite il Gateway ma direttamente nel MS)
#Si possono configurare pià istanze di retry con i nomi che abbiamo assegnato al parametro name dell'annotazione @Retry
#In Questo caso non è stato neccessario perchè abbiamo una sola istanza e questa configurazione di default viene presa in considerazione solo da lei
#Ma in altri casi le configurazioni(configs)  sarebbero scritte come figlie della proprietà resilience4j.retry.instances.<nome_istanza>.configs...
resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500 #Per valori superiori a quello di default del cicuit breaker attivato per il Ms accounts bisogna sovrascriverlo nel configurazione del circuit breaker
      enableExponentialBackoff: true
      exponential-backoff-multiplier: 2